version: "3"
services:
  app:
    cpus: 4
    mem_limit: 8g
    build:
      context: ../..
      dockerfile: ./.devcontainer/Dockerfile
    image: datajoint/workflow-calcium-imaging-demo:0.2.0
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    volumes:
      - ../../..:/workspaces:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: tail -f /dev/null
